apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-estudiantes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-estudiantes
  minReplicas: {{ .Values.estudiantes.spec.minReplicaCount }}
  maxReplicas: {{ .Values.estudiantes.spec.maxReplicaCount }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.estudiantes.spec.averageUtilization }}
