apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-estudiantes-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.estudiantes.ingress.class }}
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-estudiantes-service
      port:
        number: {{ .Values.estudiantes.service.port }}