apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: prometheus
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.3.1
    helm.sh/chart: grafana-7.3.0
  name: {{ .Release.Name }}-prometheus-grafana
  namespace: default
spec:
  
  ports:
  - name: {{ .Values.prometheus.spec.ports.name }}
    port: {{ .Values.prometheus.spec.ports.port }}
    protocol: {{ .Values.prometheus.spec.ports.protocol }}
    targetPort: {{ .Values.prometheus.spec.ports.targetPort }}
  selector:
    app.kubernetes.io/instance: {{ .Values.prometheus.spec.selector.instance }}
    app.kubernetes.io/name: {{ .Values.prometheus.spec.selector.name }}
  type: {{ .Values.prometheus.spec.type }}