apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-mysql-pv
spec:
  capacity:
    storage: {{ .Values.mysql.pv.spec.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  local:
    path: /mnt/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: {{ .Values.mysql.pv.spec.key }}
          operator: In
          values:
          - {{ .Values.mysql.pv.spec.values }}